# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvBr1VujoIixi0R7XgGmUgs6Yy_IKkiq
"""

import requests
from bs4 import BeautifulSoup
#comic website
website=  requests.get("https://readcomiconline.li/").text
bwebsite = BeautifulSoup(website,'html')
comics = bwebsite.find_all("div",class_="sub-col-1")
for comic in comics:
  title = comic.find('a').text
  print(title)

# used my local machine because collab refused to cooperate.
from importlib import import_module
from bs4 import BeautifulSoup
import selenium
from selenium import webdriver
import requests
import time

driver= webdriver.Firefox()
driver.get('https://www.carrefouregypt.com/mafegy/en/')
time.sleep(5)  # Wait for the page to load completely
care = driver.page_source
bcare = BeautifulSoup(care,'html')
categories = bcare.find_all('div','css-1jmpwbh')
for category in categories:
    print(category.text)
driver.quit()

#made in my local machine as well
from turtle import pos
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.firefox_profile import FirefoxProfile
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from bs4 import BeautifulSoup
import time

# Path to your custom Firefox profile
file_path = r"C:\Users\Mustafa Ammar\AppData\Roaming\Mozilla\Firefox\Profiles\18t1ecng.sprofile"


fprofile = FirefoxProfile(file_path)


options = Options()
options.profile = fprofile

driver = webdriver.Firefox(options=options)

driver.get('https://x.com/home')
time.sleep(14)


tweet_box = driver.find_element(By.CLASS_NAME, 'public-DraftStyleDefault-block.public-DraftStyleDefault-ltr')
action = ActionChains(driver)
action.move_to_element(tweet_box).click().send_keys("this is a test to send a tweet by selenium").perform()
time.sleep(10)

post_button = driver.find_element(By.CLASS_NAME,"css-175oi2r.r-sdzlij.r-1phboty.r-rs99b7.r-lrvibr.r-1cwvpvk.r-2yi16.r-1qi8awa.r-3pj75a.r-o7ynqc.r-6416eg.r-icoktb r-1ny4l3l")
action.move_to_element(post_button).click().perform()
driver.quit()

from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.firefox_profile import FirefoxProfile
from bs4 import BeautifulSoup
import time

file_path = r"C:\Users\Mustafa Ammar\AppData\Roaming\Mozilla\Firefox\Profiles\18t1ecng.sprofile"
fprofile = FirefoxProfile(file_path)


options = Options()
options.profile = fprofile
driver = webdriver.Firefox(options=options)


driver.get('https://www.youtube.com/feed/channels')
time.sleep(5)

page = driver.page_source
soup = BeautifulSoup(page, 'html.parser')
channel_names =soup.find_all('div','style-scope ytd-channel-name')
channel_subscribers = soup.find_all('span','style-scope ytd-channel-renderer')
count =0
for name in channel_names:
    channel_title = name.find('yt-formatted-string').text
    print(channel_title)
    print(channel_subscribers[count].text)
    count += 1
driver.quit()