# -*- coding: utf-8 -*-
"""task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fx0oX-ruZS3xOa_GOvPE5DkDM9zdkNnr
"""



"""## **1- Write a Python program to find the area of a triangle**"""

base = int(input("Enter the base of your triangle: "))
height = int(input("Enter the height of your triangle: "))
# area of a triangle  = 0.5 * base* height
area= 0.5*base*height
print("the area of your triangle is: ",area)

"""# **2- Write a Python program to swap two variables.**

"""

x=input("enter your first variable x:  ")
y= input("enter your second variable y: ")
#use three way swap
z=x
x=y
y=z
print("your first variable x has become: ",x)
print("and your second variable y has become: ",y)

"""# **3-Write a Python program to enter a number from user and convert this number from kilometers to miles.**

"""

kilometers = float(input("enter the kilometers you want to convert to miles: "))
miles = kilometers*0.621371
print("the amount of kilometers you entered in miles is: ",miles)